### ISSUE TITLE
Plan initial content for website

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/about#1]
The raison d'être for this organization: building a quick and easy website for people to be able to find information about COVID-19 and how to find resources for their open source ecosystem problems. 

This website needs to have the following minimally:

- What the mission of the website is: "Helping the open source community weather the coronavirus"
- Where to find information on Coronavirus: (elsewhere)
- What sort of resources we offer:
	- Reverse scholarships
	- Why you should cancel your meetup / conference / gathering
	- Resources for holding remote conferences
		- Remote hackathons?
	- Resources for working remotely or at home
	- Identifying organizations that need funding which normally comes from conferences to continue their work
	- Identifying at-risk individuals and projects
	- Help facilitiating aid within your OSPO or company
	- Tech resources for health workers working on coronavirus
- A way to get in touch publicly
- A way to get in touch privately
- How to get involved with this WG
- Sponsors
- A standard CoC for this space
- License and legal liability waiver

**Comment by DuaneOBrien** [comment]
I think we could streamline the content even further in order to get to a faster MVP.

* Mission
* External Resources
* Contact Options (open an issue or google form)
* Get Involved

We could seed Issue Templates to handle the different kinds of help requests (Help Organizing Virtual Events, Release/Developer Support, Individual Financial Relief, Organizational/Project Financial Relief, etc) with a fairly open ended Google Form for people to raise more discrete requests. 

If we start here, we can expand on the external resources and break them into distinct categories, peeling non-MVP content off into separate issues.

**Comment by DuaneOBrien** [comment]
I believe this issue can now be closed.

**Comment by RichardLitt** [comment]
Thanks.
